namespace Currency.Class.Enums
{
    enum CodeValute
    {
        ALL=0,
        AUD =1,
        AZN =2,
        GBP =3,
        AMD =4,
        BYN =5,
        BGN =6,
        BRL =7,
        HUF =8,
        VND =9,
        HKD =10,
        GEL =11,
        DKK =12,
        AED =13,
        USD =14,
        EUR =15,
        EGP =16,
        INR =17,
        IDR =18,
        KZT =19,
        CAD =20,
        QAR =21,
        KGS =22,
        CNY =23,
        MDL =24,
        NZD =25,
        NOK =26,
        PLN =27,
        RON =28,
        XDR =29,
        SGD =30,
        TJS =31,
        THB =32,
        TRY =33,
        TMT =34,
        UZS =35,
        UAH =36,
        CZK =37,
        SEK =38,
        CHF =39,
        RSD =40,
        ZAR =41,
        KRW =42,
        JPY =43
    }
}
